type: default-flatpaks
notify: true
system:
  install:
    # internet
    - org.mozilla.firefox
    - org.mozilla.Thunderbird
    - org.qbittorrent.qBittorrent
    - io.gitlab.news_flash.NewsFlash
    - org.nicotine_plus.Nicotine

    # chat
    - org.gajim.Gajim
    - in.cinny.Cinny
    - chat.revolt.RevoltDesktop
    - org.signal.Signal
    - dev.vencord.Vesktop

    # gaming
    - org.DolphinEmu.dolphin-emu
    - io.github.dosbox-staging
    - org.freedesktop.Platform.VulkanLayer.gamescope
    - org.freedesktop.Platform.VulkanLayer.MangoHud//22.08
    - org.prismlauncher.PrismLauncher
    - net.davidotek.pupgui2
    - org.libretro.RetroArch
    - org.vinegarhq.Vinegar

    # office
    - org.libreoffice.LibreOffice
    - md.obsidian.Obsidian

      # utilities
    - com.bitwarden.desktop
    - com.usebottles.bottles
    - fr.handbrake.ghb
    - org.kde.okteta

    # system applications
    - org.kde.kclock
    - org.kde.filelight
    - org.kde.kamoso
    - org.kde.kfind
    - org.kde.kweather
    - org.kde.gwenview
    - org.kde.kalk
    - org.kde.okular
    - org.pipewire.Helvum
    - org.gnome.DejaDup
    - com.github.tchx84.Flatseal
    - org.gustavoperedo.FontDownloader
    - io.podman_desktop.PodmanDesktop

user:
  repo-name: flathub-user
  repo-title: "Flathub (user)"
